version: '3.9'

services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    command: python manage.py runserver 0.0.0.0:8000

#    volumes:
#      - ./code/:/code/
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: shop_db
#    volumes:
#      - ~/.pg/pg_data/shop:/var/lib/postgresql/data
    env_file:
      - .env

